apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tiktok-brigade
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob.yaml
  - cronjob-export.yaml

images:
  - name: tiktok-brigade
    newName: rg.fr-par.scw.cloud/djnd/tiktok-brigade
    newTag: 'f02ea5784fd257bba534f2ae2183de7119a6dcf4'
