apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tiktok-brigade
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob.yaml

images:
  - name: tiktok-brigade
    newName: rg.fr-par.scw.cloud/djnd/tiktok-brigade
    newTag: 'latest'
