apiVersion: v1
kind: Service
metadata:
  name: tiktok-brigade
spec:
  selector:
    app: tiktok-brigade
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: tiktok-brigade-nginx
spec:
  selector:
    app: tiktok-brigade
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
